# Generated by Django 5.0.2 on 2024-02-27 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('mse', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2', models.FloatField()),
                ('inertia_path', models.CharField(max_length=100)),
                ('silhouette_path', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prediction',
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('num_passengers', models.IntegerField()),
                ('sales_channel', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=100)),
                ('purchase_lead', models.IntegerField()),
                ('length_of_stay', models.IntegerField()),
                ('flight_hour', models.IntegerField()),
                ('flight_day', models.CharField(max_length=3)),
                ('route', models.CharField(max_length=100)),
                ('booking_origin', models.CharField(max_length=100)),
                ('wants_extra_baggage', models.BooleanField()),
                ('wants_preferred_seat', models.BooleanField()),
                ('wants_in_flight_meals', models.BooleanField()),
                ('flight_duration', models.FloatField()),
                ('booking_complete', models.BooleanField()),
                ('prediction_value', models.FloatField()),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.prediction')),
            ],
            options={
                'db_table': 'prediction_result',
            },
        ),
        migrations.CreateModel(
            name='SVMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('confusion_matrix_base64', models.TextField()),
                ('classification_report', models.TextField()),
                ('cv_mean_accuracy', models.FloatField()),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svm_results', to='core.prediction')),
            ],
            options={
                'db_table': 'prediction_svm_result',
            },
        ),
    ]
